# Generated by Django 4.2.4 on 2023-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recyclable', models.CharField(choices=[('glass', 'Glass'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('batteries', 'Batteries')], max_length=20)),
                ('organic', models.CharField(choices=[('food_waste', 'Food_waste'), ('compost', 'Compost'), ('animal waste', 'Animal waste')], max_length=20)),
            ],
        ),
    ]
